-- Reference schema for the Attribute Procedurals Supabase/PostgreSQL database.
-- Django migrations remain the application source of truth.

create table if not exists contact_messages (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  email varchar(254) not null,
  company varchar(160) not null default '',
  project_type varchar(80) not null,
  message text not null,
  status varchar(20) not null default 'new',
  is_read boolean not null default false,
  source varchar(40) not null default 'website',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contact_messages_status_created_idx
  on contact_messages(status, created_at desc);
create index if not exists contact_messages_email_idx
  on contact_messages(email);

create table if not exists projects (
  id bigint generated by default as identity primary key,
  title varchar(180) not null,
  slug varchar(200) unique not null,
  summary varchar(600) not null,
  description text not null default '',
  category varchar(100) not null default '',
  technologies jsonb not null default '[]'::jsonb,
  image_url varchar(200) not null default '',
  project_url varchar(200) not null default '',
  github_url varchar(200) not null default '',
  is_featured boolean not null default false,
  is_published boolean not null default false,
  published_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists projects_published_idx
  on projects(is_published, published_at desc);
create index if not exists projects_category_idx
  on projects(category);

create table if not exists research_projects (
  id bigint generated by default as identity primary key,
  title varchar(180) not null,
  slug varchar(200) unique not null,
  summary varchar(700) not null,
  research_area varchar(120) not null,
  methodology text not null default '',
  status varchar(80) not null default 'Ongoing',
  publication_url varchar(200) not null default '',
  is_published boolean not null default false,
  published_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists research_area_idx on research_projects(research_area);
create index if not exists research_published_idx
  on research_projects(is_published, published_at desc);

create table if not exists insights (
  id bigint generated by default as identity primary key,
  title varchar(220) not null,
  slug varchar(240) unique not null,
  excerpt varchar(500) not null,
  body text not null,
  author varchar(120) not null default '',
  tags jsonb not null default '[]'::jsonb,
  cover_image_url varchar(200) not null default '',
  is_published boolean not null default false,
  published_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists insights_published_idx
  on insights(is_published, published_at desc);

create table if not exists technologies (
  id bigint generated by default as identity primary key,
  name varchar(100) unique not null,
  category varchar(100) not null,
  website_url varchar(200) not null default '',
  logo_url varchar(200) not null default '',
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists team_members (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  role varchar(120) not null,
  bio text not null default '',
  photo_url varchar(200) not null default '',
  linkedin_url varchar(200) not null default '',
  github_url varchar(200) not null default '',
  sort_order integer not null default 0,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists site_settings (
  id bigint generated by default as identity primary key,
  key varchar(100) unique not null,
  value text not null default '',
  description varchar(240) not null default ''
);
