from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("website", "0001_initial")]
    operations = [
        migrations.AddField(model_name="contactmessage", name="status", field=models.CharField(choices=[("new", "New"), ("in_progress", "In progress"), ("replied", "Replied"), ("closed", "Closed")], default="new", max_length=20)),
        migrations.AddField(model_name="contactmessage", name="source", field=models.CharField(default="website", max_length=40)),
        migrations.AddField(model_name="contactmessage", name="updated_at", field=models.DateTimeField(auto_now=True)),
        migrations.CreateModel(name="Insight", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("title", models.CharField(max_length=220)), ("slug", models.SlugField(blank=True, max_length=240, unique=True)), ("excerpt", models.TextField(max_length=500)), ("body", models.TextField()), ("author", models.CharField(blank=True, max_length=120)), ("tags", models.JSONField(blank=True, default=list)), ("cover_image_url", models.URLField(blank=True)), ("is_published", models.BooleanField(default=False)), ("published_at", models.DateTimeField(blank=True, null=True))]),
        migrations.CreateModel(name="Project", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("title", models.CharField(max_length=180)), ("slug", models.SlugField(blank=True, max_length=200, unique=True)), ("summary", models.TextField(max_length=600)), ("description", models.TextField(blank=True)), ("category", models.CharField(blank=True, max_length=100)), ("technologies", models.JSONField(blank=True, default=list)), ("image_url", models.URLField(blank=True)), ("project_url", models.URLField(blank=True)), ("github_url", models.URLField(blank=True)), ("is_featured", models.BooleanField(default=False)), ("is_published", models.BooleanField(default=False)), ("published_at", models.DateTimeField(blank=True, null=True))]),
        migrations.CreateModel(name="ResearchProject", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("title", models.CharField(max_length=180)), ("slug", models.SlugField(blank=True, max_length=200, unique=True)), ("summary", models.TextField(max_length=700)), ("research_area", models.CharField(max_length=120)), ("methodology", models.TextField(blank=True)), ("status", models.CharField(default="Ongoing", max_length=80)), ("publication_url", models.URLField(blank=True)), ("is_published", models.BooleanField(default=False)), ("published_at", models.DateTimeField(blank=True, null=True))]),
        migrations.CreateModel(name="SiteSetting", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("key", models.CharField(max_length=100, unique=True)), ("value", models.TextField(blank=True)), ("description", models.CharField(blank=True, max_length=240))]),
        migrations.CreateModel(name="TeamMember", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=120)), ("role", models.CharField(max_length=120)), ("bio", models.TextField(blank=True)), ("photo_url", models.URLField(blank=True)), ("linkedin_url", models.URLField(blank=True)), ("github_url", models.URLField(blank=True)), ("sort_order", models.PositiveIntegerField(default=0)), ("is_visible", models.BooleanField(default=True))]),
        migrations.CreateModel(name="Technology", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("name", models.CharField(max_length=100, unique=True)), ("category", models.CharField(max_length=100)), ("website_url", models.URLField(blank=True)), ("logo_url", models.URLField(blank=True)), ("sort_order", models.PositiveIntegerField(default=0)), ("is_visible", models.BooleanField(default=True))]),
        migrations.AddIndex(model_name="contactmessage", index=models.Index(fields=["status", "-created_at"], name="website_con_status_3e9e7c_idx")),
        migrations.AddIndex(model_name="contactmessage", index=models.Index(fields=["email"], name="website_con_email_5e9a3c_idx")),
        migrations.AddIndex(model_name="project", index=models.Index(fields=["is_published", "-published_at"], name="website_pro_is_publ_6a7b12_idx")),
        migrations.AddIndex(model_name="project", index=models.Index(fields=["category"], name="website_pro_categor_7f3b41_idx")),
        migrations.AddIndex(model_name="researchproject", index=models.Index(fields=["research_area"], name="website_res_researc_5d7a8e_idx")),
        migrations.AddIndex(model_name="researchproject", index=models.Index(fields=["is_published", "-published_at"], name="website_res_is_publ_6f1e2c_idx")),
        migrations.AddIndex(model_name="insight", index=models.Index(fields=["is_published", "-published_at"], name="website_ins_is_publ_8e4c31_idx")),
    ]
