# Generated by Django 5.2.17 on 2026-09-26 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_content_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_featured', '-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='researchproject',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['key']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='website_con_status_6aade9_idx',
            old_name='website_con_status_3e9e7c_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='website_con_email_94b501_idx',
            old_name='website_con_email_5e9a3c_idx',
        ),
        migrations.RenameIndex(
            model_name='insight',
            new_name='website_ins_is_publ_244142_idx',
            old_name='website_ins_is_publ_8e4c31_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='website_pro_is_publ_05eb41_idx',
            old_name='website_pro_is_publ_6a7b12_idx',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='website_pro_categor_c99a6d_idx',
            old_name='website_pro_categor_7f3b41_idx',
        ),
        migrations.RenameIndex(
            model_name='researchproject',
            new_name='website_res_researc_26d08f_idx',
            old_name='website_res_researc_5d7a8e_idx',
        ),
        migrations.RenameIndex(
            model_name='researchproject',
            new_name='website_res_is_publ_f7b8f1_idx',
            old_name='website_res_is_publ_6f1e2c_idx',
        ),
    ]
